import { FormEvent, useEffect, useRef, useState } from 'react'
import type { TerminalEntry } from '../types/game'
export function Terminal({history,onCommand}:{history:TerminalEntry[];onCommand:(command:string)=>void}){
 const [value,setValue]=useState('');const historyRef=useRef<HTMLDivElement>(null);const inputRef=useRef<HTMLInputElement>(null)
 useEffect(()=>{const element=historyRef.current;if(element)element.scrollTo({top:element.scrollHeight,behavior:'smooth'});inputRef.current?.focus({preventScroll:true})},[history])
 const submit=(e:FormEvent)=>{e.preventDefault();const command=value.trim();if(!command)return;onCommand(command);setValue('')}
 return <section onClick={()=>inputRef.current?.focus({preventScroll:true})} className="terminal-panel flex h-[60vh] min-h-[420px] max-h-[640px] flex-col overflow-hidden rounded-2xl border border-slate-800 bg-[#050a12] shadow-2xl shadow-black/20">
  <div className="flex items-center justify-between border-b border-slate-800 bg-slate-900/80 px-4 py-3"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full bg-rose-500"/><span className="h-2.5 w-2.5 rounded-full bg-amber-400"/><span className="h-2.5 w-2.5 rounded-full bg-emerald-500"/></div><span className="font-mono text-xs text-slate-500">embedded-git-lab — simulator</span></div>
  <div ref={historyRef} className="min-h-0 flex-1 space-y-4 overflow-y-auto p-4 font-mono text-sm leading-6" aria-live="polite">{history.length===0&&<div className="text-slate-500">Ketik <span className="text-emerald-400">help</span> untuk melihat command yang didukung.</div>}{history.map((item,i)=><div key={i}>{item.command&&<div className="text-slate-200"><span className="text-emerald-400">learner@octa</span><span className="text-slate-500">:</span><span className="text-cyan-300">~/firmware</span>$ {item.command}</div>}{item.output&&item.output!=='__CLEAR__'&&<pre className={`mt-1 whitespace-pre-wrap font-mono ${item.kind==='error'?'text-rose-300':item.kind==='success'?'text-emerald-200':'text-slate-400'}`}>{item.output}</pre>}</div>)}</div>
  <form onSubmit={submit} className="flex items-center gap-2 border-t border-slate-800 bg-slate-950 px-4 py-3 font-mono text-sm"><span className="text-emerald-400">$</span><input ref={inputRef} autoFocus value={value} onChange={e=>setValue(e.target.value)} className="min-w-0 flex-1 bg-transparent text-slate-100 outline-none placeholder:text-slate-700" placeholder="git status" aria-label="Terminal command"/><button className="rounded-lg bg-emerald-500 px-3 py-1.5 font-sans text-xs font-semibold text-slate-950 hover:bg-emerald-400">Jalankan</button></form>
 </section>
}
