import { useState } from 'react'
import { Award, BookOpen, Check, ChevronRight, CircleDot, Cpu, FileCode2, GitBranch, Lightbulb, RotateCcw, Save, TerminalSquare, Trophy } from 'lucide-react'
import { Terminal } from './components/Terminal'
import { levelInfo, missionById, missions } from './data/missions'
import { runGitCommand } from './engine/gitSimulator'
import { advanceObjectives, completedObjectivePrefix } from './engine/missionProgress'
import { useAutosave } from './hooks/useAutosave'
import type { GameSession, Mission } from './types/game'

const initialMission=missions[0]
const makeSession=(mission:Mission,progress?:GameSession['progress']):GameSession=>({repository:structuredClone(mission.initialState),terminal:[{command:'',output:`Misi ${mission.id}: ${mission.title}\n${mission.briefing}`,kind:'info'}],checkpoint:structuredClone(mission.initialState),checkpointObjectives:[],progress:progress??{xp:0,completedMissions:[],achievements:[],activeMissionId:mission.id,hintUsage:{}}})
const defaultSession=makeSession(initialMission)

export default function App(){
 const [session,setSession,clearSave]=useAutosave<GameSession>('embedded-git-lab:v1.0:session',defaultSession)
 const mission=missionById(session.progress.activeMissionId)
 const [selectedLevel,setSelectedLevel]=useState(mission.level)
 const [tab,setTab]=useState<'mission'|'repo'|'files'>('mission')
 const [dismissedCompletion,setDismissedCompletion]=useState<string|null>(null)
 const doneIds=completedObjectivePrefix(mission,session.checkpointObjectives??[])
 const complete=doneIds.length===mission.objectives.length
 const hintCount=session.progress.hintUsage[mission.id]??0
 const nextMission=missions[missions.findIndex(m=>m.id===mission.id)+1]
 const startMission=(m:Mission)=>{setDismissedCompletion(null);setSession(prev=>makeSession(m,{...prev.progress,activeMissionId:m.id}))}
 const run=(command:string)=>setSession(prev=>{
   const before=prev.checkpointObjectives??[]
   const result=runGitCommand(prev.repository,command)
   const terminal=result.output==='__CLEAR__'?[]:[...prev.terminal,{command,output:result.output,kind:result.kind}]
   const after=advanceObjectives(mission,result.state,before)
   let progress={...prev.progress};let checkpoint=prev.checkpoint;let checkpointObjectives=before
   if(after.length>before.length){checkpoint=structuredClone(result.state);checkpointObjectives=after;terminal.push({command:'',output:`✓ Objective tercapai (${after.length}/${mission.objectives.length}). Checkpoint diperbarui.`,kind:'success'})}
   if(after.length===mission.objectives.length&&!progress.completedMissions.includes(mission.id)){
     const earned=Math.max(30,mission.xp-(progress.hintUsage[mission.id]??0)*15);progress={...progress,xp:progress.xp+earned,completedMissions:[...progress.completedMissions,mission.id]};terminal.push({command:'',output:`🏆 Misi selesai! +${earned} XP`,kind:'success'})
     if((progress.hintUsage[mission.id]??0)===0&&!progress.achievements.includes('zero-hint'))progress.achievements=[...progress.achievements,'zero-hint']
     if(progress.completedMissions.length===missions.length&&!progress.achievements.includes('release-engineer'))progress.achievements=[...progress.achievements,'release-engineer']
   }
   return {...prev,repository:result.state,terminal,progress,checkpoint,checkpointObjectives}
 })
 const useHint=()=>setSession(prev=>({...prev,progress:{...prev.progress,hintUsage:{...prev.progress.hintUsage,[mission.id]:Math.min(mission.hints.length,(prev.progress.hintUsage[mission.id]??0)+1)}}}))
 const resetMission=()=>{setDismissedCompletion(null);setSession(prev=>makeSession(mission,{...prev.progress,activeMissionId:mission.id}))}
 const restoreCheckpoint=()=>session.checkpoint&&setSession(prev=>({...prev,repository:structuredClone(prev.checkpoint!),terminal:[...prev.terminal,{command:'',output:'↺ State dikembalikan ke checkpoint terakhir.',kind:'info'}]}))
 return <main className="min-h-screen bg-slate-950 text-slate-100">
  <header className="sticky top-0 z-20 border-b border-slate-800/80 bg-slate-950/90 backdrop-blur"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-4 px-5 py-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-500/15 text-emerald-400"><Cpu size={22}/></div><div><div className="text-xs font-semibold uppercase tracking-[.22em] text-emerald-400">Embedded Engineering Workstation</div><h1 className="text-xl font-bold">Embedded Git Lab <span className="text-xs font-medium text-slate-500">v1.0</span></h1></div></div><div className="flex items-center gap-3 text-sm"><div className="hidden items-center gap-2 rounded-full border border-slate-800 px-3 py-2 text-slate-300 sm:flex"><Save size={15} className="text-emerald-400"/>Autosave aktif</div><div className="flex items-center gap-2 rounded-full bg-amber-400/10 px-3 py-2 font-semibold text-amber-300"><Trophy size={16}/>{session.progress.xp} XP</div></div></div></header>
  <div className="mx-auto grid max-w-[1500px] gap-5 px-5 py-5 xl:grid-cols-[260px_minmax(0,1fr)_360px]">
   <aside className="rounded-2xl border border-slate-800 bg-slate-900/45 p-3 xl:sticky xl:top-24 xl:h-[calc(100vh-7rem)] xl:overflow-y-auto"><div className="px-2 pb-3 text-xs font-semibold uppercase tracking-wider text-slate-500">Learning path</div>{levelInfo.map(l=><div key={l.level} className="mb-2"><button onClick={()=>setSelectedLevel(l.level)} className={`w-full rounded-xl px-3 py-3 text-left transition ${selectedLevel===l.level?'bg-slate-800 text-white':'text-slate-400 hover:bg-slate-900'}`}><div className="flex items-center gap-2"><span className="grid h-6 w-6 place-items-center rounded-md bg-slate-950 text-xs">{l.level}</span><span className="font-semibold">{l.title}</span></div><div className="mt-1 pl-8 text-xs text-slate-500">{l.caption}</div></button>{selectedLevel===l.level&&<div className="mt-1 space-y-1 pl-2">{missions.filter(m=>m.level===l.level).map(m=><button key={m.id} onClick={()=>startMission(m)} className={`flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-xs ${mission.id===m.id?'bg-emerald-500/10 text-emerald-300':'text-slate-500 hover:bg-slate-900 hover:text-slate-300'}`}>{session.progress.completedMissions.includes(m.id)?<Check size={14}/>:<CircleDot size={14}/>}<span className="truncate">{m.id} · {m.title}</span></button>)}</div>}</div>)}</aside>
   <section className="min-w-0 space-y-5"><div className="rounded-2xl border border-slate-800 bg-gradient-to-br from-slate-900 to-slate-950 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-emerald-400"><BookOpen size={14}/>{mission.mode==='challenge'?'Challenge':'Tutorial'} · Level {mission.level}</div><h2 className="mt-2 text-2xl font-bold">{mission.title}</h2><p className="mt-1 text-sm text-slate-400">{mission.subtitle}</p></div><div className="rounded-xl border border-slate-800 bg-slate-950/70 px-4 py-3 text-right"><div className="text-xs text-slate-500">Progress misi</div><div className="mt-1 font-mono text-lg font-bold text-emerald-300">{doneIds.length}/{mission.objectives.length}</div></div></div><p className="mt-4 max-w-3xl text-sm leading-6 text-slate-300">{mission.briefing}</p></div>
    <Terminal history={session.terminal} onCommand={run}/>
   </section>
   <aside className="space-y-4 xl:sticky xl:top-24 xl:h-[calc(100vh-7rem)] xl:overflow-y-auto"><div className="flex rounded-xl border border-slate-800 bg-slate-900/50 p-1 text-xs">{(['mission','repo','files'] as const).map(t=><button key={t} onClick={()=>setTab(t)} className={`flex-1 rounded-lg px-2 py-2 capitalize ${tab===t?'bg-slate-800 text-white':'text-slate-500'}`}>{t}</button>)}</div>
    {tab==='mission'&&<><section className="rounded-2xl border border-slate-800 bg-slate-900/45 p-5"><h3 className="flex items-center gap-2 font-semibold"><TerminalSquare size={17} className="text-emerald-400"/>Objective</h3><div className="mt-4 space-y-3">{mission.objectives.map(o=>{const d=doneIds.includes(o.id);return <div key={o.id} className="flex gap-3 text-sm"><span className={`mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full border ${d?'border-emerald-500 bg-emerald-500 text-slate-950':'border-slate-700 text-transparent'}`}>{d&&<Check size={13}/>}</span><span className={d?'text-slate-500 line-through':'text-slate-300'}>{o.label}</span></div>})}</div></section><section className="rounded-2xl border border-slate-800 bg-slate-900/45 p-5"><div className="flex items-center justify-between"><h3 className="flex items-center gap-2 font-semibold"><Lightbulb size={17} className="text-amber-300"/>Hint</h3><span className="text-xs text-slate-600">-{15} XP / hint</span></div>{hintCount>0?<div className="mt-3 space-y-2 text-sm leading-6 text-slate-400">{mission.hints.slice(0,hintCount).map((h,i)=><p key={i}><span className="mr-2 font-mono text-amber-300">{i+1}.</span>{h}</p>)}</div>:<p className="mt-3 text-sm text-slate-500">Gunakan hint jika benar-benar diperlukan.</p>}<button onClick={useHint} disabled={hintCount>=mission.hints.length} className="mt-4 w-full rounded-xl border border-slate-700 px-3 py-2 text-sm hover:bg-slate-800 disabled:opacity-40">Buka hint berikutnya</button></section></>}
    {tab==='repo'&&<section className="rounded-2xl border border-slate-800 bg-slate-900/45 p-5"><h3 className="flex items-center gap-2 font-semibold"><GitBranch size={17} className="text-cyan-300"/>Repository state</h3><dl className="mt-4 space-y-3 text-sm"><Row k="Branch aktif" v={session.repository.currentBranch}/><Row k="HEAD" v={session.repository.branches[session.repository.currentBranch]??'-'}/><Row k="Upstream" v={session.repository.upstream??'-'}/><Row k="Commits" v={String(Object.keys(session.repository.commits).length)}/><Row k="Stash" v={String(session.repository.stash.length)}/><Row k="Tags" v={Object.keys(session.repository.tags).join(', ')||'-'}/><Row k="PR" v={String(session.repository.pullRequests.length)}/><Row k="Releases" v={String(session.repository.releases.length)}/></dl><div className="mt-5 border-t border-slate-800 pt-4"><div className="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-500">Branches</div>{Object.entries(session.repository.branches).map(([b,c])=><div key={b} className="mb-2 flex items-center gap-2 font-mono text-xs"><span className={b===session.repository.currentBranch?'text-emerald-400':'text-slate-600'}>●</span><span className="min-w-0 flex-1 truncate text-slate-300">{b}</span><span className="text-slate-600">{c}</span></div>)}</div></section>}
    {tab==='files'&&<section className="rounded-2xl border border-slate-800 bg-slate-900/45 p-5"><h3 className="flex items-center gap-2 font-semibold"><FileCode2 size={17} className="text-violet-300"/>Virtual files</h3><div className="mt-4 space-y-2">{session.repository.files.map(f=><div key={f.path} className="flex items-center justify-between gap-3 rounded-lg bg-slate-950/60 px-3 py-2 font-mono text-xs"><span className="truncate text-slate-300">{f.path}</span><span className={stateColor(f.state)}>{f.state}</span></div>)}</div></section>}
    <section className="rounded-2xl border border-slate-800 bg-slate-900/45 p-4"><div className="grid grid-cols-2 gap-2"><button onClick={restoreCheckpoint} className="flex items-center justify-center gap-2 rounded-xl border border-slate-700 px-3 py-2 text-xs hover:bg-slate-800"><RotateCcw size={14}/>Checkpoint</button><button onClick={resetMission} className="flex items-center justify-center gap-2 rounded-xl border border-slate-700 px-3 py-2 text-xs hover:bg-slate-800"><RotateCcw size={14}/>Reset misi</button></div><button onClick={()=>{if(confirm('Hapus seluruh progress lokal?'))clearSave()}} className="mt-2 w-full text-center text-[11px] text-slate-600 hover:text-rose-400">Hapus seluruh save lokal</button></section>
    <section className="rounded-2xl border border-slate-800 bg-slate-900/45 p-4"><div className="flex items-center gap-2 text-sm font-semibold"><Award size={16} className="text-amber-300"/>Achievement</div><div className="mt-3 text-xs text-slate-500">{session.progress.achievements.length?session.progress.achievements.join(' · '):'Belum ada. Selesaikan misi tanpa hint untuk membuka achievement.'}</div></section>
   </aside>
  </div>
  {complete&&dismissedCompletion!==mission.id&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/85 p-5 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="mission-complete-title"><div className="w-full max-w-xl rounded-3xl border border-emerald-400/30 bg-slate-900 p-8 text-center shadow-2xl shadow-emerald-950/50"><div className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-emerald-400 text-slate-950"><Trophy size={40}/></div><div className="mt-6 text-xs font-semibold uppercase tracking-[.24em] text-emerald-400">Mission accomplished</div><h2 id="mission-complete-title" className="mt-2 text-3xl font-bold">Misi berhasil diselesaikan</h2><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-slate-400">Seluruh objective untuk <span className="font-semibold text-slate-200">{mission.id} · {mission.title}</span> telah tercapai.</p><div className="mt-6 rounded-2xl border border-slate-800 bg-slate-950/70 p-4"><div className="text-sm text-slate-400">Progress objective</div><div className="mt-1 font-mono text-2xl font-bold text-emerald-300">{doneIds.length}/{mission.objectives.length}</div></div><div className="mt-7 flex flex-col-reverse justify-center gap-3 sm:flex-row"><button onClick={()=>setDismissedCompletion(mission.id)} className="rounded-xl border border-slate-700 px-5 py-3 text-sm font-semibold text-slate-300 hover:bg-slate-800">Tinjau hasil</button>{nextMission?<button autoFocus onClick={()=>{startMission(nextMission);setSelectedLevel(nextMission.level)}} className="flex items-center justify-center gap-2 rounded-xl bg-emerald-400 px-5 py-3 font-semibold text-slate-950 hover:bg-emerald-300">Misi berikutnya<ChevronRight size={18}/></button>:<button autoFocus onClick={()=>setDismissedCompletion(mission.id)} className="rounded-xl bg-emerald-400 px-5 py-3 font-semibold text-slate-950 hover:bg-emerald-300">Selesaikan learning path</button>}</div></div></div>}
 </main>
}
function Row({k,v}:{k:string;v:string}){return <div className="flex items-center justify-between gap-3"><dt className="text-slate-500">{k}</dt><dd className="truncate font-mono text-xs text-slate-300">{v}</dd></div>}
function stateColor(s:string){return s==='staged'?'text-emerald-300':s==='modified'?'text-amber-300':s==='untracked'?'text-cyan-300':s==='ignored'?'text-slate-600':s==='deleted'?'text-rose-300':'text-slate-500'}
